import fs from "node:fs";
import path from "node:path";
import { loadQuestions, QUESTIONS_ROOT } from "../questions/lib";

interface Verdict {
  id: string;
  correct_idx: number;
  evidence: string;
}

export const ALL_VERDICTS: Verdict[] = [
  // --- CINEMA (Lot 1) ---
  { id: "film-star-wars-year", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Star_Wars,_%C3%A9pisode_IV_:_Un_nouvel_espoir" },
  { id: "film-millennium-falcon", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Faucon_Millenium" },
  { id: "film-harry-potter-actor", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Daniel_Radcliffe" },
  { id: "film-bond-dr-no", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Sean_Connery" },
  { id: "film-godfather-vito", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Marlon_Brando" },
  { id: "film-jaws-shark", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Les_Dents_de_la_mer" },
  { id: "film-pulp-fiction-director", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Quentin_Tarantino" },
  { id: "film-chevre-depardieu-richard", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/La_Ch%C3%A8vre" },
  { id: "film-bronzes-saga", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Les_Bronz%C3%A9s" },
  { id: "film-gendarme-st-tropez", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Le_Gendarme_de_Saint-Tropez" },
  { id: "film-amelie-director", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Jean-Pierre_Jeunet" },
  { id: "film-walle-eve", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/WALL-E" },
  { id: "film-shrek-studio", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/DreamWorks_Animation" },
  { id: "film-toy-story-woody-voice", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Tom_Hanks" },
  { id: "film-reine-neiges-soeurs", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/La_Reine_des_neiges_(film,_2013)" },
  { id: "film-inception-nolan", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Inception" },
  { id: "film-joker-ledger", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Heath_Ledger" },
  { id: "film-lotr-ring-bearer", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Frodon_Sacquet" },
  { id: "film-harry-potter-studio", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Warner_Bros." },
  { id: "film-iron-man-actor", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Robert_Downey_Jr." },
  { id: "film-matrix-neo", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Neo_(Matrix)" },
  { id: "film-titanic-famous-line", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Titanic_(film,_1997)" },
  { id: "film-scarface-quote", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Scarface_(film,_1983)" },
  { id: "film-taxi-driver-quote", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Taxi_Driver" },
  { id: "film-oscars-record-11", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Ben-Hur_(film,_1959)" },
  { id: "film-oscars-actress-4", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Katharine_Hepburn" },
  { id: "film-oscars-will-smith", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/94e_c%C3%A9r%C3%A9monie_des_Oscars" },
  { id: "film-goodfellas-director", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Martin_Scorsese" },
  { id: "film-blade-runner-director", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Ridley_Scott" },
  { id: "film-citizen-kane", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Citizen_Kane" },
  { id: "film-avatar-pandora", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Pandora_(Avatar)" },
  { id: "film-jurassic-park-director", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Steven_Spielberg" },
  { id: "film-gladiator-maximus", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Russell_Crowe" },
  { id: "film-amelie-arrondissement", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Montmartre" },
  { id: "film-intouchables-actor", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Omar_Sy" },
  { id: "film-bienvenue-chtis-record", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Bienvenue_chez_les_Ch%27tis" },
  { id: "film-leon-besson", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/L%C3%A9on_(film)" },
  { id: "film-la-la-land-director", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Damien_Chazelle" },
  { id: "film-inception-totem", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Inception" },
  { id: "film-ghibli-studio-prod", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Studio_Ghibli" },
  { id: "film-artist-best-picture", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/The_Artist" },
  { id: "film-bttf-director", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Robert_Zemeckis" },
  { id: "film-oscars-meryl", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Meryl_Streep" },
  { id: "film-forrest-gump-actor", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Forrest_Gump" },

  // --- MANGA & ANIME (Lot 2) ---
  { id: "anime-naruto-author", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Masashi_Kishimoto" },
  { id: "anime-akira-kaneda", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Sh%C5%8Dtar%C5%8D_Kaneda" },
  { id: "anime-totoro", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Mon_voisin_Totoro" },
  { id: "anime-porco-rosso", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Porco_Rosso" },
  { id: "anime-attack-on-titan-eren", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Eren_J%C3%A4ger" },
  { id: "anime-sailor-moon-usagi", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Usagi_Tsukino" },
  { id: "anime-death-note-ryuk", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Ryuk_(Death_Note)" },
  { id: "anime-fullmetal-brothers", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Fullmetal_Alchemist" },
  { id: "anime-one-punch-saitama", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/One_Punch_Man" },
  { id: "anime-demon-slayer-nezuko", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Demon_Slayer:_Kimetsu_no_Yaiba" },
  { id: "anime-kiki-job", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Kiki_la_petite_sorci%C3%A8re" },
  { id: "anime-howls-magic", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Le_Ch%C3%A2teau_ambulant" },
  { id: "anime-mha-one-for-all", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/My_Hero_Academia" },
  { id: "anime-hxh-exam", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Hunter_%C3%97_Hunter" },
  { id: "anime-chihiro-bathhouse", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Le_Voyage_de_Chihiro" },
  { id: "anime-vegeta-prince", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Vegeta" },
  { id: "anime-slam-dunk", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Slam_Dunk_(manga)" },
  { id: "anime-wind-rises", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Le_Vent_se_l%C3%A8ve_(film,_2013)" },

  // --- SERIES (Lot 2) ---
  { id: "tv-stranger-things-11", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Stranger_Things" },
  { id: "tv-sherlock-baker-street", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/221B_Baker_Street" },
  { id: "tv-doctor-who-species", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Seigneurs_du_Temps" },
  { id: "tv-casa-de-papel-cities", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/La_casa_de_papel" },
  { id: "tv-squid-game-456", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Squid_Game" },
  { id: "tv-pokemon-sacha", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Sacha_(Pok%C3%A9mon)" },
  { id: "tv-true-detective-cohle", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/True_Detective" },
  { id: "tv-house-cane", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Dr_House" },
  { id: "tv-got-dracarys", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Game_of_Thrones" },
  { id: "tv-friends-monica-chef", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Monica_Geller" },
  { id: "tv-simpsons-maggie", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Maggie_Simpson" },
  { id: "tv-twin-peaks-cooper", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Dale_Cooper" },
  { id: "tv-xfiles-mulder", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Fox_Mulder" },
  { id: "tv-grey-anatomy-heroine", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Meredith_Grey" },
  { id: "tv-himym-barney", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Barney_Stinson" },
  { id: "tv-prison-break-scofield", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Michael_Scofield" },
  { id: "tv-mentalist-jane", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Simon_Baker" },
  { id: "tv-lost-flight", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Lost_:_Les_Disparus" },
  { id: "tv-community-greendale", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Community_(s%C3%A9rie_t%C3%A9l%C3%A9vis%C3%A9e)" },
  { id: "tv-office-jim-pranks", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Jim_Halpert" },
  { id: "tv-dexter-miami", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Dexter_(s%C3%A9rie_t%C3%A9l%C3%A9vis%C3%A9e)" },
  { id: "tv-got-hodor", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Hodor" },
  { id: "tv-supernatural-brothers", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Supernatural_(s%C3%A9rie_t%C3%A9l%C3%A9vis%C3%A9e)" },

  // --- GAMING (Lot 3) ---
  { id: "game-mario-brother", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Luigi" },
  { id: "game-mario-company", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Nintendo" },
  { id: "game-zelda-princess", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Princesse_Zelda" },
  { id: "game-ff7-cloud", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Cloud_Strife" },
  { id: "game-gta-vice-city", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Grand_Theft_Auto:_Vice_City" },
  { id: "game-minecraft-best-seller", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Minecraft" },
  { id: "game-cs-bomb", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Counter-Strike" },
  { id: "game-skyrim-dovahkiin", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/The_Elder_Scrolls_V:_Skyrim" },
  { id: "game-mario-first", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Donkey_Kong_(jeu_vid%C3%A9o)" },
  { id: "game-witcher-author", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Andrzej_Sapkowski" },
  { id: "game-zelda-ocarina", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/The_Legend_of_Zelda:_Ocarina_of_Time" },
  { id: "game-halo-chief", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Master_Chief" },
  { id: "game-lara-croft", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Lara_Croft" },
  { id: "game-resident-evil-city", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Raccoon_City" },
  { id: "game-ryu-hadoken", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Hadouken" },
  { id: "game-tetris-pieces", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/T%C3%A9tromino" },
  { id: "game-roblox-platform", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Roblox" },
  { id: "game-sims-creator", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Will_Wright" },
  { id: "game-zelda-first", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/The_Legend_of_Zelda_(jeu_vid%C3%A9o)" },
  { id: "game-gameboy", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Game_Boy" },
  { id: "game-xbox-company", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Microsoft" },
  { id: "game-kingdom-hearts", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Kingdom_Hearts" },
  { id: "game-starcraft-rts", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/StarCraft" },

  // --- MUSIQUE (Lot 3) ---
  { id: "music-freddie-mercury", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Freddie_Mercury" },
  { id: "music-beatles-members", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Mick_Jagger" },
  { id: "music-thriller-album", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Thriller_(album)" },
  { id: "music-saxophone-inventor", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Adolphe_Sax" },
  { id: "music-rap-bronx", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Hip-hop" },
  { id: "music-reggae-origin", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Reggae" },
  { id: "music-fado-country", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Fado" },
  { id: "music-tango-country", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Tango_(danse)" },
  { id: "music-pavarotti-nessun", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Luciano_Pavarotti" },
  { id: "music-iam-marseille", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/IAM" },
  { id: "music-mc-solaar", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/MC_Solaar" },
  { id: "music-indila-derniere", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Indila" },
  { id: "music-gims-sap", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Gims" },
  { id: "music-vianney-beau-papa", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Vianney_(chanteur)" },
  { id: "music-kendji-the-voice", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Kendji_Girac" },
  { id: "music-adele-rolling", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Rolling_in_the_Deep" },
  { id: "music-bts-country", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/BTS_(groupe)" },
  { id: "music-candle-in-the-wind", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Candle_in_the_Wind" },
  { id: "music-aretha-soul", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Aretha_Franklin" },
  { id: "music-johnny-cash-ring", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Johnny_Cash" },
  { id: "music-bob-dylan-nobel", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Bob_Dylan" },
  { id: "music-u2-bono", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Bono" },
  { id: "music-green-day", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Green_Day" },

  // --- FOOD & FOOTBALL & SPORT & INTERNET & TECH & INSOLITE (Lot 4) ---
  { id: "food-margherita-colors", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Pizza_Margherita" },
  { id: "food-tacos", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Taco" },
  { id: "food-foie-gras", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Foie_gras" },
  { id: "food-cassoulet", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Cassoulet" },
  { id: "food-baguette-unesco", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Baguette_de_pain" },
  { id: "food-champagne", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Champagne_(AOC)" },
  { id: "food-pastis", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Pastis" },
  { id: "food-macaron", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Macaron" },
  { id: "food-hamburger", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Hamburger" },
  { id: "food-sushi-rice", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Sushi" },
  { id: "food-truffle", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Tuber_melanosporum" },
  { id: "food-vanilla-orchid", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Vanille" },
  { id: "food-cocoa-origin", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Cacao" },
  { id: "food-dijon", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Moutarde_de_Dijon" },
  { id: "food-camembert", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Camembert_(fromage)" },
  { id: "food-comte", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Comt%C3%A9_(fromage)" },
  { id: "food-tapas", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Tapas_(gastronomie)" },
  { id: "food-bagel", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Bagel" },

  { id: "foot-france-1998", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Finale_de_la_Coupe_du_monde_de_football_1998" },
  { id: "foot-wc-2022", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Coupe_du_monde_de_football_2022" },
  { id: "foot-ronaldo-record", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Cristiano_Ronaldo" },
  { id: "foot-pele-titles", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Pel%C3%A9" },
  { id: "foot-ucl", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Ligue_des_champions_de_l%27UEFA" },
  { id: "foot-psg-stadium", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Parc_des_Princes" },
  { id: "foot-france-euros", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/%C3%89quipe_de_France_de_football_au_Championnat_d%27Europe" },
  { id: "foot-zidane-clubs", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Zin%C3%A9dine_Zidane" },
  { id: "foot-bayern", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Bayern_Munich" },
  { id: "foot-klose", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Miroslav_Klose" },

  { id: "odd-hiccup-record", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Charles_Osborne_(record)" },
  { id: "odd-camel-humps", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Chameau" },
  { id: "odd-lightning-frequency", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Foudre" },
  { id: "odd-milky-way-light", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Voie_lact%C3%A9e" },
  { id: "odd-google-garage", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Google" },

  { id: "web-twitter-bird", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Twitter" },
  { id: "web-snapchat-ghost", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Snapchat" },
  { id: "web-linkedin", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/LinkedIn" },
  { id: "web-wikipedia-wales", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Jimmy_Wales" },
  { id: "web-first-email", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Ray_Tomlinson" },
  { id: "web-grumpy-cat", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Grumpy_Cat" },
  { id: "web-rick-astley", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Rick_Astley" },
  { id: "web-emoji-japan", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/%C3%89moji" },
  { id: "web-404", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Erreur_HTTP_404" },
  { id: "web-doodles", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Google_Doodle" },
  { id: "web-first-youtube-video", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Me_at_the_zoo" },
  { id: "web-deep-web", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Web_invisible" },
  { id: "web-chrome", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Google_Chrome" },

  { id: "sport-olympics-1896", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Jeux_olympiques_de_1896" },
  { id: "sport-olympic-rings", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Symbole_olympique" },
  { id: "sport-olympic-motto", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Devise_olympique" },
  { id: "sport-bolt-time", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Usain_Bolt" },
  { id: "sport-marathon-origin", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Philippid%C3%A8s" },
  { id: "sport-roland-garros", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Internationaux_de_France_de_tennis" },
  { id: "sport-phelps-swimming", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Michael_Phelps" },
  { id: "sport-yellow-jersey", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Maillot_jaune" },
  { id: "sport-nba-usa", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/National_Basketball_Association" },
  { id: "sport-jordan-23", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Michael_Jordan" },
  { id: "sport-volleyball-morgan", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/William_G._Morgan" },
  { id: "sport-schumacher-ferrari", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Scuderia_Ferrari" },
  { id: "sport-handball-france", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/%C3%89quipe_de_France_masculine_de_handball" },
  { id: "sport-ali-quote", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Mohamed_Ali" },
  { id: "sport-paris-2024", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Jeux_olympiques_d%27%C3%A9t%C3%A9_de_2024" },
  { id: "sport-milliat", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Alice_Milliat" },

  { id: "tech-lightbulb", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Thomas_Edison" },
  { id: "tech-arpanet", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/ARPANET" },
  { id: "tech-apple-founders", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Apple" },
  { id: "tech-google-founders", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Google" },
  { id: "tech-amazon-founder", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Jeff_Bezos" },
  { id: "tech-ibm-simon", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/IBM_Simon" },
  { id: "tech-snake-game", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Snake_(genre_de_jeux_vid%C3%A9o)" },
  { id: "tech-ibm-pc", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/IBM_PC" },
  { id: "tech-mouse-engelbart", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Douglas_Engelbart" },
  { id: "tech-bluetooth-king", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Harald_%C3%A0_la_dent_bleue" },
  { id: "tech-robot-word", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Karel_%C4%8Capek" },
  { id: "tech-turing-father", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Alan_Turing" },
  { id: "tech-babbage", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Charles_Babbage" },
  { id: "tech-velcro", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/George_de_Mestral" },
  { id: "tech-google-googol", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Gogol_(nombre)" },
  { id: "tech-netflix-dvd", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Netflix" },
  { id: "tech-ampere-unit", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Amp%C3%A8re" },
  { id: "tech-qwerty", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/QWERTY" },

  // --- LITTERATURE & SCIENCE (Lot 5) ---
  { id: "book-hugo-miserables", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Les_Mis%C3%A9rables" },
  { id: "book-dumas-musketeers", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Alexandre_Dumas" },
  { id: "book-dartagnan", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/D%27Artagnan" },
  { id: "book-verne-nautilus", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Nautilus_(Jules_Verne)" },
  { id: "book-verne-nemo", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Vingt_Mille_Lieues_sous_les_mers" },
  { id: "book-flaubert", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Gustave_Flaubert" },
  { id: "book-zola-germinal", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Germinal_(roman)" },
  { id: "book-proust", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/%C3%80_la_recherche_du_temps_perdu" },
  { id: "book-camus-nobel", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Albert_Camus" },
  { id: "book-saint-exupery", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Antoine_de_Saint-Exup%C3%A9ry" },
  { id: "book-pagnol", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Marcel_Pagnol" },
  { id: "book-rimbaud-age", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Arthur_Rimbaud" },
  { id: "book-moliere-avare", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/L%27Avare" },
  { id: "book-la-fontaine", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Jean_de_La_Fontaine" },
  { id: "book-tolstoi", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/L%C3%A9on_Tolsto%C3%AF" },
  { id: "book-orwell-1984", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/1984_(roman)" },
  { id: "book-ministry-of-love", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Minist%C3%A8res_de_1984" },
  { id: "book-tolkien", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/J._R._R._Tolkien" },
  { id: "book-rowling", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/J._K._Rowling" },
  { id: "book-christie-66", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Agatha_Christie" },
  { id: "book-miss-marple", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Miss_Marple" },
  { id: "book-goncourt", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Prix_Goncourt" },
  { id: "book-le-clezio", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/J._M._G._Le_Cl%C3%A9zio" },
  { id: "book-ernaux", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Annie_Ernaux" },
  { id: "book-apollinaire", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Guillaume_Apollinaire" },
  { id: "book-grimm", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Fr%C3%A8res_Grimm" },

  { id: "sci-gravity-newton", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Isaac_Newton" },
  { id: "sci-light-speed", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Vitesse_de_la_lumi%C3%A8re" },
  { id: "sci-earth-core", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Noyau_terrestre" },
  { id: "sci-gold-au", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Or" },
  { id: "sci-salt-nacl", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Chlorure_de_sodium" },
  { id: "sci-helium-balloons", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/H%C3%A9lium" },
  { id: "sci-lavoisier", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Antoine_Lavoisier" },
  { id: "sci-photosynthesis-inputs", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Photosynth%C3%A8se" },
  { id: "sci-stomach-acid", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Acide_chlorhydrique" },
  { id: "sci-hummingbird", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Trochilidae" },
  { id: "sci-blue-whale", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Baleine_bleue" },
  { id: "sci-giraffe-vertebrae", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Girafe" },
  { id: "sci-kangaroo", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Kangourou" },
  { id: "sci-blood-groups", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Groupe_sanguin" },
  { id: "sci-black-hole", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Trou_noir" },
  { id: "sci-comet-tail", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Com%C3%A8te" },
  { id: "sci-venus-hottest", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/V%C3%A9nus_(plan%C3%A8te)" },
  { id: "sci-emc2", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/E%3Dmc2" },
  { id: "sci-eureka", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Archim%C3%A8de" },
  { id: "sci-magnet-poles", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Aimant" },
  { id: "sci-ozone", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Couche_d%27ozone" },
  { id: "sci-everest", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Everest" },
  { id: "sci-nile", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Nil" },
  { id: "sci-leap-year", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Ann%C3%A9e_bissextile" },

  // --- CULTURE GENERALE (Lot 7) ---
  { id: "cg-mon-cheops", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Pyramide_de_Kh%C3%A9ops" },
  { id: "cg-mon-versailles", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Ch%C3%A2teau_de_Versailles" },
  { id: "cg-mon-nimes", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Ar%C3%A8nes_de_N%C3%AEmes" },
  { id: "cg-mon-vatican", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Chapelle_Sixtine" },
  { id: "cg-flag-canada", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Drapeau_du_Canada" },
  { id: "cg-flag-suisse", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Drapeau_de_la_Suisse" },
  { id: "cg-flag-usa-etoiles", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Drapeau_des_%C3%89tats-Unis" },
  { id: "cg-flag-union-jack", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Union_Jack" },
  { id: "cg-flag-italie", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Drapeau_de_l%27Italie" },
  { id: "cg-ani-plus-rapide", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Gu%C3%A9pard" },
  { id: "cg-ani-poulpe", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Pieuvre" },
  { id: "cg-ani-ornithorynque", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Ornithorynque" },
  { id: "cg-ani-araignee", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Araign%C3%A9e" },
  { id: "cg-ani-colombe", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Colombe_de_la_paix" },
  { id: "cg-corps-organe", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Peau_humaine" },
  { id: "cg-corps-bebe", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Squelette_humain" },
  { id: "cg-corps-coeur", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/C%C5%93ur" },
  { id: "cg-corps-abo", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Syst%C3%A8me_ABO" },
  { id: "cg-corps-donneur", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Donneur_universel" },
  { id: "cg-alim-pomme", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Fruit_d%C3%A9fendu" },
  { id: "cg-alim-guacamole", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Guacamole" },
  { id: "cg-alim-emmental", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Emmental" },
  { id: "cg-alim-vin", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Vin" },
  { id: "cg-alim-banane", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Banane" },
  { id: "cg-alim-yaourt", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Yaourt" },
  { id: "cg-cap-canada", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Ottawa" },
  { id: "cg-cap-bresil", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Brasilia" },
  { id: "cg-cap-turquie", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Ankara" },
  { id: "cg-cap-afrique-sud", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Pretoria" },
  { id: "cg-cap-inde", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/New_Delhi" },
  { id: "cg-xx-titanic-bateau", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Titanic" },
  { id: "cg-xx-concorde", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Concorde_(avion)" },
  { id: "cg-xx-spoutnik-annee", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Spoutnik_1" },
  { id: "cg-xx-1969-tv", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Apollo_11" },
  { id: "cg-xx-mur-1961", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Mur_de_Berlin" },
  { id: "cg-ins-fuseaux", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Fuseau_horaire" },
  { id: "cg-ins-soleil", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Soleil" },
  { id: "cg-ins-mandarin", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Mandarin_(langue)" },
  { id: "cg-ins-asie", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Asie" },
  { id: "cg-geo-seychelles", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Seychelles" },
  { id: "cg-geo-gibraltar", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/D%C3%A9troit_de_Gibraltar" },
  { id: "cg-geo-nigeria", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Nigeria" },
  { id: "cg-sci-azote", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Azote" },
  { id: "cg-sci-einstein", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Albert_Einstein" },
  { id: "cg-sci-mars", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Mars_(plan%C3%A8te)" },
  { id: "cg-art-velasquez", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Diego_V%C3%A9lasquez" },
  { id: "cg-art-hugo", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Victor_Hugo" },
  { id: "cg-art-petit-prince", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Antoine_de_Saint-Exup%C3%A9ry" },
  { id: "cg-sport-hiver", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Jeux_olympiques_d%27hiver" },
  { id: "cg-sport-foot", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Football" },
  { id: "cg-sport-phelps", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Michael_Phelps" },
  { id: "cg-ins-etoile-mer", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Asteroidea" },
  { id: "cg-ins-journee-venus", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/V%C3%A9nus_(plan%C3%A8te)" },
  { id: "cg-ins-saturne", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Saturne_(plan%C3%A8te)" },
  { id: "cg-exp-31", correct_idx: 3, evidence: "https://fr.wiktionary.org/wiki/se_mettre_sur_son_trente-et-un" },
  { id: "cg-exp-chair-poule", correct_idx: 1, evidence: "https://fr.wiktionary.org/wiki/avoir_la_chair_de_poule" },
  { id: "cg-exp-yeux-tete", correct_idx: 3, evidence: "https://fr.wiktionary.org/wiki/co%C3%BBter_les_yeux_de_la_t%C3%AAte" },
  { id: "cg-exp-fromage", correct_idx: 1, evidence: "https://fr.wiktionary.org/wiki/en_faire_tout_un_fromage" },
  { id: "cg-exp-taureau", correct_idx: 3, evidence: "https://fr.wiktionary.org/wiki/prendre_le_taureau_par_les_cornes" },
  { id: "cg-exp-sellette", correct_idx: 1, evidence: "https://fr.wiktionary.org/wiki/%C3%AAtre_sur_la_sellette" },
  { id: "cg-exp-cafard", correct_idx: 3, evidence: "https://fr.wiktionary.org/wiki/avoir_le_cafard" },
  { id: "cg-exp-mouron", correct_idx: 1, evidence: "https://fr.wiktionary.org/wiki/se_faire_du_mouron" },
  { id: "cg-exp-pommes", correct_idx: 3, evidence: "https://fr.wiktionary.org/wiki/tomber_dans_les_pommes" },
  { id: "cg-exp-coup-main", correct_idx: 1, evidence: "https://fr.wiktionary.org/wiki/donner_un_coup_de_main" },
  { id: "cg-exp-chaussettes", correct_idx: 3, evidence: "https://fr.wiktionary.org/wiki/avoir_le_moral_dans_les_chaussettes" },
  { id: "cg-exp-grasse-matinee", correct_idx: 1, evidence: "https://fr.wiktionary.org/wiki/faire_la_grasse_matin%C3%A9e" },
  { id: "cg-exp-pain-planche", correct_idx: 3, evidence: "https://fr.wiktionary.org/wiki/avoir_du_pain_sur_la_planche" },
  { id: "cg-exp-temps-chien", correct_idx: 1, evidence: "https://fr.wiktionary.org/wiki/temps_de_chien" },
  { id: "cg-exp-vache", correct_idx: 3, evidence: "https://fr.wiktionary.org/wiki/parler_fran%C3%A7ais_comme_une_vache_espagnole" },
  { id: "cg-rec-russie", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Russie" },
  { id: "cg-rec-mariannes", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Fosse_des_Mariannes" },
  { id: "cg-rec-faucon", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Faucon_p%C3%A8lerin" },
  { id: "cg-rec-frontiere", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Fronti%C3%A8re_entre_le_Canada_et_les_%C3%89tats-Unis" },
  { id: "cg-rec-groenland", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Groenland" },
  { id: "cg-rec-baikal", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Lac_Ba%C3%AFkal" },
  { id: "cg-rec-jo", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/%C3%89tats-Unis_aux_Jeux_olympiques" },
  { id: "cg-rec-bolt-annee", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Championnats_du_monde_d%27athl%C3%A9tisme_2009" },
  { id: "cg-rec-bresil-5", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/%C3%89quipe_du_Br%C3%A9sil_de_football" },
  { id: "cg-rec-bible", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Bible" },
  { id: "cg-rec-journee-terre", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Rotation_de_la_Terre" },
  { id: "cg-rec-musulmans", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Indon%C3%A9sie" },
  { id: "cg-rec-tokyo", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Grand_Tokyo" },
  { id: "cg-rec-araignee-web", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Caerostris_darwini" },

  // --- HISTOIRE (Lot 8) ---
  { id: "war-dec-gama", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Vasco_de_Gama" },
  { id: "war-dec-pizarro", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Francisco_Pizarro" },
  { id: "war-dec-cook", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/James_Cook" },
  { id: "war-indus-rail-1827", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Ligne_de_Saint-%C3%89tienne_%C3%A0_Andr%C3%A9zieux" },
  { id: "war-indus-bell", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Alexander_Graham_Bell" },
  { id: "war-indus-rocket", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/George_Stephenson" },
  { id: "war-indus-benz", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Carl_Benz" },
  { id: "war-gf-rideau-fer", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Rideau_de_fer" },
  { id: "war-gf-varsovie", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Pacte_de_Varsovie" },
  { id: "war-gf-mur-berlin", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Mur_de_Berlin" },
  { id: "war-gf-cuba-annee", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Crise_des_missiles_de_Cuba" },
  { id: "war-gf-lune-1969", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Apollo_11" },
  { id: "war-gf-reagan", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Empire_du_Mal" },
  { id: "war-gf-afghanistan", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Guerre_d%27Afghanistan_(1979-1989)" },
  { id: "war-coree-parallele", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/38e_parall%C3%A8le_nord" },
  { id: "war-coree-chine", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Guerre_de_Cor%C3%A9e" },
  { id: "war-vietnam-giap", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/V%C3%B5_Nguy%C3%AAn_Gi%C3%A1p" },
  { id: "war-vietnam-tet", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Offensive_du_T%C3%AAt" },
  { id: "war-cs-sud", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/%C3%89tats_conf%C3%A9d%C3%A9r%C3%A9s_d%27Am%C3%A9rique" },
  { id: "war-cs-davis", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Jefferson_Davis" },
  { id: "war-cs-gettysburg", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Bataille_de_Gettysburg" },
  { id: "war-cs-antietam", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Bataille_d%27Antietam" },
  { id: "war-cs-grant", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Ulysses_S._Grant" },
  { id: "war-cs-sherman", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/William_Tecumseh_Sherman" },
  { id: "war-cs-ford", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Assassinat_d%27Abraham_Lincoln" },
  { id: "war-cs-13e", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Treizi%C3%A8me_amendement_de_la_Constitution_des_%C3%89tats-Unis" },
  { id: "war-marathon-roi-perse", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Darius_Ier" },
  { id: "war-thermopyles-300", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Bataille_des_Thermopyles" },
  { id: "war-thermopyles-roi", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/L%C3%A9onidas_Ier_de_Sparte" },
  { id: "war-salamine-strategie", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Th%C3%A9mistocle" },
  { id: "war-xerxes-invasion", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Xerx%C3%A8s_Ier" },
  { id: "war-peloponnese-adversaires", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Guerre_du_P%C3%A9loponn%C3%A8se" },
  { id: "war-peloponnese-fin", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Guerre_du_P%C3%A9loponn%C3%A8se" },
  { id: "war-peloponnese-sicile", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Exp%C3%A9dition_de_Sicile" },
  { id: "war-alexandre-precepteur", correct_idx: 0, evidence: "https://fr.wikipedia.org/wiki/Aristote" },
  { id: "war-alexandre-granique", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Bataille_du_Granique" },
  { id: "war-alexandre-gaugameles", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Bataille_de_Gaugam%C3%A8les" },
  { id: "war-alexandre-alexandrie", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Alexandrie" },
  { id: "war-alexandre-noeud", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/N%C5%93ud_gordien" },
  { id: "war-alexandre-age", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Alexandre_le_Grand" },
  { id: "war-puniques-1ere-annee", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki_Premi%C3%A8re_guerre_punique" },
  { id: "war-puniques-alpes", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Passage_des_Alpes_par_Hannibal" },
  { id: "war-puniques-zama", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Bataille_de_Zama" },
  { id: "war-puniques-caton", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Caton_l%27Ancien" },
  { id: "war-ww1-assassinat", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Attentat_de_Sarajevo" },
  { id: "war-ww1-triple-entente", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Triple-Entente" },
  { id: "war-ww1-tranchees", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Guerre_de_tranch%C3%A9es" },
  { id: "war-ww1-verdun-annee", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Bataille_de_Verdun" },
  { id: "war-ww1-somme", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Bataille_de_la_Somme" },
  { id: "war-ww1-taxis", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Taxis_de_la_Marne" },
  { id: "war-ww1-wilson", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Woodrow_Wilson" },
  { id: "war-ww1-brest-litovsk", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Trait%C3%A9_de_Brest-Litovsk" },
  { id: "war-ww1-armistice-heure", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Armistice_de_1918" },
  { id: "war-ww1-versailles", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Trait%C3%A9_de_Versailles" },
  { id: "war-ww1-gaz", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Gaz_de_combat_de_la_Premi%C3%A8re_Guerre_mondiale" },
  { id: "war-ww1-tommies", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Tommy_(militaire)" },
  { id: "war-ww1-guillaume2", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Guillaume_II_(empereur_allemand)" },
  { id: "war-ww1-morts-francais", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Pertes_humaines_de_la_Premi%C3%A8re_Guerre_mondiale" },
  { id: "war-ww1-ypres", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Deuxi%C3%A8me_bataille_d%27Ypres" },
  { id: "war-ww1-mutineries", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Mutineries_de_1917" },
  { id: "war-ww2-pologne", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Campagne_de_Pologne_(1939)" },
  { id: "war-ww2-blitzkrieg", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Blitzkrieg" },
  { id: "war-ww2-appel-18-juin", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Appel_du_18_Juin" },
  { id: "war-ww2-bataille-angleterre", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Bataille_d%27Angleterre" },
  { id: "war-ww2-barbarossa-annee", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Op%C3%A9ration_Barbarossa" },
  { id: "war-ww2-stalingrad-fin", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Bataille_de_Stalingrad" },
  { id: "war-ww2-el-alamein", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Seconde_bataille_d%27El_Alamein" },
  { id: "war-ww2-overlord", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Op%C3%A9ration_Overlord" },
  { id: "war-ww2-dragoon", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/D%C3%A9barquement_de_Provence" },
  { id: "war-ww2-potsdam-truman", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Conf%C3%A9rence_de_Potsdam" },
  { id: "war-ww2-8-mai", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Actes_de_capitulation_de_l%27Allemagne_nazie" },
  { id: "war-ww2-annee-atomique", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Bombardements_atomiques_d%27Hiroshima_et_de_Nagasaki" },
  { id: "war-ww2-2-septembre", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Actes_de_capitulation_du_Japon" },
  { id: "war-ww2-wannsee", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Conf%C3%A9rence_de_Wannsee" },
  { id: "war-ww2-dynamo", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/%C3%89vacuation_de_Dunkerque" },
  { id: "war-ww2-mussolini", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Benito_Mussolini" },
  { id: "war-ww2-torch", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Op%C3%A9ration_Torch" },
  { id: "war-nap-pie7", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Pie_VII" },
  { id: "war-nap-austerlitz", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Bataille_d%27Austerlitz" },
  { id: "war-nap-tilsit", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Trait%C3%A9s_de_Tilsit" },
  { id: "war-nap-russie-1812", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Campagne_de_Russie" },
  { id: "war-nap-berezina", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Bataille_de_la_B%C3%A9r%C3%A9zina" },
  { id: "war-nap-abdication-1814", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Premi%C3%A8re_abdication_de_Napol%C3%A9on_Ier" },
  { id: "war-nap-retour-1815", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Cent-Jours" },
  { id: "war-nap-waterloo", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Bataille_de_Waterloo" },
  { id: "war-nap-sainte-helene", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Sainte-H%C3%A9l%C3%A8ne_(%C3%AEle)" },
  { id: "war-nap-code-civil", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Code_civil_(France)" },
  { id: "war-croisade-pape", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Urbain_II" },
  { id: "war-croisade-godefroy", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Godefroy_de_Bouillon" },
  { id: "war-croisade-hattin", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Bataille_de_Hattin" },
  { id: "war-croisade-acre-1291", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Si%C3%A8ge_de_Saint-Jean-d%27Acre_(1291)" },
  { id: "war-croisade-molay", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Jacques_de_Molay" },
  { id: "war-cent-ans-adversaires", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Guerre_de_Cent_Ans" },
  { id: "war-cent-ans-plantagenets", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Maison_Plantagen%C3%AAt" },
  { id: "war-cent-ans-poitiers", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Bataille_de_Poitiers_(1356)" },
  { id: "war-cent-ans-henri5", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Henri_V_(roi_d%27Angleterre)" },
  { id: "war-cent-ans-orleans", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Si%C3%A8ge_d%27Orl%C3%A9ans_(1428-1429)" },
  { id: "war-cent-ans-jeanne-mort", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Jeanne_d%27Arc" },
  { id: "war-cent-ans-castillon", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Bataille_de_Castillon" },
  { id: "war-moyen-age-charlemagne", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Charlemagne" },
  { id: "war-moyen-age-peste", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Peste_noire" },
  { id: "war-moyen-age-serre", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Servage" },
  { id: "war-moyen-age-adoubement", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Adoubement" },
  { id: "war-ren-berceau", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Florence" },
  { id: "war-ren-sixtine", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Plafond_de_la_chapelle_Sixtine" },
  { id: "war-ren-colomb", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Christophe_Colomb" },
  { id: "war-ren-chambord", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Ch%C3%A2teau_de_Chambord" },
  { id: "war-ren-imprimerie", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Imprimerie" },
  { id: "war-ren-catherine", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Catherine_de_M%C3%A9dicis" },
  { id: "war-rev-bastille", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Prise_de_la_Bastille" },
  { id: "war-rev-jeu-de-paume", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Serment_du_Jeu_de_paume" },
  { id: "war-rev-ddhc", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/D%C3%A9claration_des_droits_de_l%27homme_et_du_citoyen_de_1789" },
  { id: "war-rev-10-aout", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Prise_des_Tuileries" },
  { id: "war-rev-louis16", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Ex%C3%A9cution_de_Louis_XVI" },
  { id: "war-rev-robespierre", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Maximilien_de_Robespierre" },
  { id: "war-rev-thermidor", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Chute_de_Robespierre" },
  { id: "war-rev-brumaire", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Coup_d%27%C3%89tat_du_18_Brumaire" },
  { id: "war-rev-marseillaise-hymne", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/La_Marseillaise" },
  { id: "war-rev-devise", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Libert%C3%A9,_%C3%89galit%C3%A9,_Fraternit%C3%A9" },
  { id: "war-rev-vendee", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Guerre_de_Vend%C3%A9e" },
  { id: "war-rome-fondation-jumeaux", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Romulus_et_R%C3%A9mus" },
  { id: "war-rome-cesar-gaule", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Guerre_des_Gaules" },
  { id: "war-rome-rubicon", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Passage_du_Rubicon" },
  { id: "war-rome-veni-vidi", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Veni,_vidi,_vici" },
  { id: "war-rome-ides-mars", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Ides_de_mars" },
  { id: "war-rome-chute-476", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/D%C3%A9clin_de_l%27Empire_romain_d%27Occident" },
  { id: "war-rome-constantinople", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Constantin_Ier_(empereur_romain)" },
  { id: "war-rome-vesuve", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/%C3%89ruption_du_V%C3%A9suve_en_79" },
  { id: "war-rome-spartacus", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Spartacus" },
  { id: "war-rome-incendie-64", correct_idx: 1, evidence: "https://fr.wikipedia.org/wiki/Grand_incendie_de_Rome" },
  { id: "war-rome-circus", correct_idx: 3, evidence: "https://fr.wikipedia.org/wiki/Circus_Maximus" }
];

// Check and output
const dataset = loadQuestions();
const byId = new Map(dataset.questions.map(q => [q.id, q]));

const validated: Verdict[] = [];
let notFound = 0;
let alreadyCorrect = 0;

for (const v of ALL_VERDICTS) {
  const q = byId.get(v.id);
  if (!q) {
    console.error(`ERROR: Question ${v.id} not found in dataset!`);
    notFound++;
    continue;
  }
  if (v.correct_idx < 0 || v.correct_idx > 3) {
    console.error(`ERROR: Question ${v.id} invalid correct_idx: ${v.correct_idx}`);
    continue;
  }
  const answerText = q.answers[v.correct_idx];
  if (!answerText) {
    console.error(`ERROR: Question ${v.id} answer at index ${v.correct_idx} is empty!`);
    continue;
  }
  if (q.correctAnswer === v.correct_idx) {
    alreadyCorrect++;
  }
  validated.push(v);
}

console.log(`Total verdicts defined: ${ALL_VERDICTS.length}`);
console.log(`Validated: ${validated.length}`);
console.log(`Already correct: ${alreadyCorrect}`);
console.log(`New corrections to apply: ${validated.length - alreadyCorrect}`);

const outFile = path.join(QUESTIONS_ROOT, ".audit-verdicts.json");
fs.writeFileSync(outFile, JSON.stringify(validated, null, 2), "utf-8");
console.log(`Wrote verdicts to ${outFile}`);
