/**
 * Free Party — World data (spec §44–45)
 * Faits stables : capitales et monnaies des pays (source : Wikidata / ISO 4217).
 * Pour les pays à capitales multiples ou controversées, la capitale officielle
 * (ou le siège du gouvernement) est utilisée avec une note si nécessaire.
 */

export interface CountryData {
  name: string;
  capital?: string;
  /** Nom français de la monnaie */
  currencyName?: string;
  /** Code ISO 4217 */
  currencyCode?: string;
  /** Symbole courant */
  currencySymbol?: string;
  /** Note sur les cas particuliers */
  note?: string;
}

export const COUNTRIES: CountryData[] = [
  { name: "Afghanistan", capital: "Kaboul", currencyName: "afghani", currencyCode: "AFN", currencySymbol: "؋" },
  { name: "Afrique du Sud", capital: "Pretoria", currencyName: "rand", currencyCode: "ZAR", currencySymbol: "R", note: "Capitale administrative (siège du gouvernement) ; Le Cap est la capitale législative." },
  { name: "Albanie", capital: "Tirana", currencyName: "lek", currencyCode: "ALL", currencySymbol: "L" },
  { name: "Algérie", capital: "Alger", currencyName: "dinar algérien", currencyCode: "DZD", currencySymbol: "DA" },
  { name: "Allemagne", capital: "Berlin", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Andorre", capital: "Andorre-la-Vieille", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Angola", capital: "Luanda", currencyName: "kwanza", currencyCode: "AOA", currencySymbol: "Kz" },
  { name: "Arabie saoudite", capital: "Riyad", currencyName: "riyal saoudien", currencyCode: "SAR", currencySymbol: "﷼" },
  { name: "Argentine", capital: "Buenos Aires", currencyName: "peso argentin", currencyCode: "ARS", currencySymbol: "$" },
  { name: "Arménie", capital: "Erevan", currencyName: "dram", currencyCode: "AMD", currencySymbol: "֏" },
  { name: "Australie", capital: "Canberra", currencyName: "dollar australien", currencyCode: "AUD", currencySymbol: "$" },
  { name: "Autriche", capital: "Vienne", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Azerbaïdjan", capital: "Bakou", currencyName: "manat azerbaïdjanais", currencyCode: "AZN", currencySymbol: "₼" },
  { name: "Bahamas", capital: "Nassau", currencyName: "dollar des Bahamas", currencyCode: "BSD", currencySymbol: "$" },
  { name: "Bahreïn", capital: "Manama", currencyName: "dinar bahreïni", currencyCode: "BHD", currencySymbol: ".د.ب" },
  { name: "Bangladesh", capital: "Dacca", currencyName: "taka", currencyCode: "BDT", currencySymbol: "৳" },
  { name: "Barbade", capital: "Bridgetown", currencyName: "dollar barbadien", currencyCode: "BBD", currencySymbol: "$" },
  { name: "Belgique", capital: "Bruxelles", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Bélize", capital: "Belmopan", currencyName: "dollar bélizien", currencyCode: "BZD", currencySymbol: "$" },
  { name: "Bénin", capital: "Porto-Novo", currencyName: "franc CFA (BCEAO)", currencyCode: "XOF", currencySymbol: "FCFA", note: "Capitale officielle ; Cotonou est la capitale économique." },
  { name: "Bhoutan", capital: "Thimphou", currencyName: "ngultrum", currencyCode: "BTN", currencySymbol: "Nu" },
  { name: "Biélorussie", capital: "Minsk", currencyName: "rouble biélorusse", currencyCode: "BYN", currencySymbol: "Br" },
  { name: "Birmanie (Myanmar)", capital: "Naypyidaw", currencyName: "kyat", currencyCode: "MMK", currencySymbol: "K" },
  { name: "Bolivie", capital: "La Paz", currencyName: "boliviano", currencyCode: "BOB", currencySymbol: "Bs", note: "La Paz : capitale administrative ; Sucre : capitale constitutionnelle." },
  { name: "Bosnie-Herzégovine", capital: "Sarajevo", currencyName: "mark convertible", currencyCode: "BAM", currencySymbol: "KM" },
  { name: "Botswana", capital: "Gaborone", currencyName: "pula", currencyCode: "BWP", currencySymbol: "P" },
  { name: "Brésil", capital: "Brasilia", currencyName: "réal brésilien", currencyCode: "BRL", currencySymbol: "R$" },
  { name: "Brunéi", capital: "Bandar Seri Begawan", currencyName: "dollar de Brunéi", currencyCode: "BND", currencySymbol: "$" },
  { name: "Bulgarie", capital: "Sofia", currencyName: "lev bulgare", currencyCode: "BGN", currencySymbol: "лв" },
  { name: "Burkina Faso", capital: "Ouagadougou", currencyName: "franc CFA (BCEAO)", currencyCode: "XOF", currencySymbol: "FCFA" },
  { name: "Burundi", capital: "Gitega", currencyName: "franc burundais", currencyCode: "BIF", currencySymbol: "FBu" },
  { name: "Cambodge", capital: "Phnom Penh", currencyName: "riel", currencyCode: "KHR", currencySymbol: "៛" },
  { name: "Cameroun", capital: "Yaoundé", currencyName: "franc CFA (BEAC)", currencyCode: "XAF", currencySymbol: "FCFA" },
  { name: "Canada", capital: "Ottawa", currencyName: "dollar canadien", currencyCode: "CAD", currencySymbol: "$" },
  { name: "Cap-Vert", capital: "Praia", currencyName: "escudo cap-verdien", currencyCode: "CVE", currencySymbol: "$" },
  { name: "Chili", capital: "Santiago", currencyName: "peso chilien", currencyCode: "CLP", currencySymbol: "$" },
  { name: "Chine", capital: "Pékin", currencyName: "yuan renminbi", currencyCode: "CNY", currencySymbol: "¥" },
  { name: "Chypre", capital: "Nicosie", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Colombie", capital: "Bogota", currencyName: "peso colombien", currencyCode: "COP", currencySymbol: "$" },
  { name: "Comores", capital: "Moroni", currencyName: "franc comorien", currencyCode: "KMF", currencySymbol: "CF" },
  { name: "Congo (RDC)", capital: "Kinshasa", currencyName: "franc congolais", currencyCode: "CDF", currencySymbol: "FC" },
  { name: "Congo (République)", capital: "Brazzaville", currencyName: "franc CFA (BEAC)", currencyCode: "XAF", currencySymbol: "FCFA" },
  { name: "Corée du Nord", capital: "Pyongyang", currencyName: "won nord-coréen", currencyCode: "KPW", currencySymbol: "₩" },
  { name: "Corée du Sud", capital: "Séoul", currencyName: "won sud-coréen", currencyCode: "KRW", currencySymbol: "₩" },
  { name: "Costa Rica", capital: "San José", currencyName: "colón", currencyCode: "CRC", currencySymbol: "₡" },
  { name: "Côte d'Ivoire", capital: "Yamoussoukro", currencyName: "franc CFA (BCEAO)", currencyCode: "XOF", currencySymbol: "FCFA", note: "Capitale officielle ; Abidjan est la capitale économique." },
  { name: "Croatie", capital: "Zagreb", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Cuba", capital: "La Havane", currencyName: "peso cubain", currencyCode: "CUP", currencySymbol: "$" },
  { name: "Danemark", capital: "Copenhague", currencyName: "couronne danoise", currencyCode: "DKK", currencySymbol: "kr" },
  { name: "Djibouti", capital: "Djibouti", currencyName: "franc djiboutien", currencyCode: "DJF", currencySymbol: "Fdj" },
  { name: "République dominicaine", capital: "Saint-Domingue", currencyName: "peso dominicain", currencyCode: "DOP", currencySymbol: "$" },
  { name: "Égypte", capital: "Le Caire", currencyName: "livre égyptienne", currencyCode: "EGP", currencySymbol: "£" },
  { name: "Émirats arabes unis", capital: "Abou Dabi", currencyName: "dirham des Émirats", currencyCode: "AED", currencySymbol: "د.إ" },
  { name: "Équateur", capital: "Quito", currencyName: "dollar américain", currencyCode: "USD", currencySymbol: "$", note: "Le dollar US est la monnaie officielle depuis 2000." },
  { name: "Érythrée", capital: "Asmara", currencyName: "nakfa", currencyCode: "ERN", currencySymbol: "Nfk" },
  { name: "Espagne", capital: "Madrid", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Estonie", capital: "Tallinn", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Eswatini", capital: "Mbabane", currencyName: "lilangeni", currencyCode: "SZL", currencySymbol: "L" },
  { name: "États-Unis", capital: "Washington D.C.", currencyName: "dollar américain", currencyCode: "USD", currencySymbol: "$" },
  { name: "Éthiopie", capital: "Addis-Abeba", currencyName: "birr", currencyCode: "ETB", currencySymbol: "Br" },
  { name: "Fidji", capital: "Suva", currencyName: "dollar fidjien", currencyCode: "FJD", currencySymbol: "$" },
  { name: "Finlande", capital: "Helsinki", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "France", capital: "Paris", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Gabon", capital: "Libreville", currencyName: "franc CFA (BEAC)", currencyCode: "XAF", currencySymbol: "FCFA" },
  { name: "Gambie", capital: "Banjul", currencyName: "dalasi", currencyCode: "GMD", currencySymbol: "D" },
  { name: "Géorgie", capital: "Tbilissi", currencyName: "lari", currencyCode: "GEL", currencySymbol: "₾" },
  { name: "Ghana", capital: "Accra", currencyName: "cédi", currencyCode: "GHS", currencySymbol: "₵" },
  { name: "Grèce", capital: "Athènes", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Guatemala", capital: "Guatemala", currencyName: "quetzal", currencyCode: "GTQ", currencySymbol: "Q" },
  { name: "Guinée", capital: "Conakry", currencyName: "franc guinéen", currencyCode: "GNF", currencySymbol: "FG" },
  { name: "Guinée-Bissau", capital: "Bissau", currencyName: "franc CFA (BCEAO)", currencyCode: "XOF", currencySymbol: "FCFA" },
  { name: "Guyana", capital: "Georgetown", currencyName: "dollar guyanais", currencyCode: "GYD", currencySymbol: "$" },
  { name: "Haïti", capital: "Port-au-Prince", currencyName: "gourde", currencyCode: "HTG", currencySymbol: "G" },
  { name: "Honduras", capital: "Tegucigalpa", currencyName: "lempira", currencyCode: "HNL", currencySymbol: "L" },
  { name: "Hongrie", capital: "Budapest", currencyName: "forint", currencyCode: "HUF", currencySymbol: "Ft" },
  { name: "Inde", capital: "New Delhi", currencyName: "roupie indienne", currencyCode: "INR", currencySymbol: "₹" },
  { name: "Indonésie", capital: "Jakarta", currencyName: "roupie indonésienne", currencyCode: "IDR", currencySymbol: "Rp" },
  { name: "Irak", capital: "Bagdad", currencyName: "dinar irakien", currencyCode: "IQD", currencySymbol: "د.ع" },
  { name: "Iran", capital: "Téhéran", currencyName: "rial iranien", currencyCode: "IRR", currencySymbol: "﷼" },
  { name: "Irlande", capital: "Dublin", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Islande", capital: "Reykjavik", currencyName: "couronne islandaise", currencyCode: "ISK", currencySymbol: "kr" },
  { name: "Israël", capital: "Jérusalem", currencyName: "shekel", currencyCode: "ILS", currencySymbol: "₪", note: "Jérusalem : capitale proclamée ; siège du gouvernement." },
  { name: "Italie", capital: "Rome", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Jamaïque", capital: "Kingston", currencyName: "dollar jamaïcain", currencyCode: "JMD", currencySymbol: "$" },
  { name: "Japon", capital: "Tokyo", currencyName: "yen", currencyCode: "JPY", currencySymbol: "¥" },
  { name: "Jordanie", capital: "Amman", currencyName: "dinar jordanien", currencyCode: "JOD", currencySymbol: "د.ا" },
  { name: "Kazakhstan", capital: "Astana", currencyName: "tenge", currencyCode: "KZT", currencySymbol: "₸" },
  { name: "Kenya", capital: "Nairobi", currencyName: "shilling kényan", currencyCode: "KES", currencySymbol: "KSh" },
  { name: "Kirghizistan", capital: "Bichkek", currencyName: "som kirghize", currencyCode: "KGS", currencySymbol: "с" },
  { name: "Koweït", capital: "Koweït", currencyName: "dinar koweïtien", currencyCode: "KWD", currencySymbol: "د.ك" },
  { name: "Laos", capital: "Vientiane", currencyName: "kip", currencyCode: "LAK", currencySymbol: "₭" },
  { name: "Lesotho", capital: "Maseru", currencyName: "loti", currencyCode: "LSL", currencySymbol: "L" },
  { name: "Lettonie", capital: "Riga", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Liban", capital: "Beyrouth", currencyName: "livre libanaise", currencyCode: "LBP", currencySymbol: "ل.ل" },
  { name: "Libéria", capital: "Monrovia", currencyName: "dollar libérien", currencyCode: "LRD", currencySymbol: "$" },
  { name: "Libye", capital: "Tripoli", currencyName: "dinar libyen", currencyCode: "LYD", currencySymbol: "ل.د" },
  { name: "Liechtenstein", capital: "Vaduz", currencyName: "franc suisse", currencyCode: "CHF", currencySymbol: "Fr" },
  { name: "Lituanie", capital: "Vilnius", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Luxembourg", capital: "Luxembourg", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Macédoine du Nord", capital: "Skopje", currencyName: "denar", currencyCode: "MKD", currencySymbol: "ден" },
  { name: "Madagascar", capital: "Antananarivo", currencyName: "ariary", currencyCode: "MGA", currencySymbol: "Ar" },
  { name: "Malaisie", capital: "Kuala Lumpur", currencyName: "ringgit", currencyCode: "MYR", currencySymbol: "RM" },
  { name: "Malawi", capital: "Lilongwe", currencyName: "kwacha malawien", currencyCode: "MWK", currencySymbol: "MK" },
  { name: "Maldives", capital: "Malé", currencyName: "rufiyaa", currencyCode: "MVR", currencySymbol: "Rf" },
  { name: "Mali", capital: "Bamako", currencyName: "franc CFA (BCEAO)", currencyCode: "XOF", currencySymbol: "FCFA" },
  { name: "Malte", capital: "La Valette", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Maroc", capital: "Rabat", currencyName: "dirham marocain", currencyCode: "MAD", currencySymbol: "د.م." },
  { name: "Maurice", capital: "Port-Louis", currencyName: "roupie mauricienne", currencyCode: "MUR", currencySymbol: "₨" },
  { name: "Mauritanie", capital: "Nouakchott", currencyName: "ouguiya", currencyCode: "MRU", currencySymbol: "UM" },
  { name: "Mexique", capital: "Mexico", currencyName: "peso mexicain", currencyCode: "MXN", currencySymbol: "$" },
  { name: "Moldavie", capital: "Chișinău", currencyName: "leu moldave", currencyCode: "MDL", currencySymbol: "L" },
  { name: "Monaco", capital: "Monaco", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Mongolie", capital: "Oulan-Bator", currencyName: "tugrik", currencyCode: "MNT", currencySymbol: "₮" },
  { name: "Monténégro", capital: "Podgorica", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Mozambique", capital: "Maputo", currencyName: "metical", currencyCode: "MZN", currencySymbol: "MT" },
  { name: "Namibie", capital: "Windhoek", currencyName: "dollar namibien", currencyCode: "NAD", currencySymbol: "$" },
  { name: "Népal", capital: "Katmandou", currencyName: "roupie népalaise", currencyCode: "NPR", currencySymbol: "₨" },
  { name: "Nicaragua", capital: "Managua", currencyName: "córdoba", currencyCode: "NIO", currencySymbol: "C$" },
  { name: "Niger", capital: "Niamey", currencyName: "franc CFA (BCEAO)", currencyCode: "XOF", currencySymbol: "FCFA" },
  { name: "Nigeria", capital: "Abuja", currencyName: "naira", currencyCode: "NGN", currencySymbol: "₦" },
  { name: "Norvège", capital: "Oslo", currencyName: "couronne norvégienne", currencyCode: "NOK", currencySymbol: "kr" },
  { name: "Nouvelle-Zélande", capital: "Wellington", currencyName: "dollar néo-zélandais", currencyCode: "NZD", currencySymbol: "$" },
  { name: "Oman", capital: "Mascate", currencyName: "rial omanais", currencyCode: "OMR", currencySymbol: "ر.ع." },
  { name: "Ouganda", capital: "Kampala", currencyName: "shilling ougandais", currencyCode: "UGX", currencySymbol: "USh" },
  { name: "Ouzbékistan", capital: "Tachkent", currencyName: "sum", currencyCode: "UZS", currencySymbol: "so'm" },
  { name: "Pakistan", capital: "Islamabad", currencyName: "roupie pakistanaise", currencyCode: "PKR", currencySymbol: "₨" },
  { name: "Panama", capital: "Panama", currencyName: "balboa", currencyCode: "PAB", currencySymbol: "B/." },
  { name: "Papouasie-Nouvelle-Guinée", capital: "Port Moresby", currencyName: "kina", currencyCode: "PGK", currencySymbol: "K" },
  { name: "Paraguay", capital: "Asuncion", currencyName: "guaraní", currencyCode: "PYG", currencySymbol: "₲" },
  { name: "Pays-Bas", capital: "Amsterdam", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€", note: "Amsterdam : capitale officielle ; La Haye : siège du gouvernement." },
  { name: "Pérou", capital: "Lima", currencyName: "sol péruvien", currencyCode: "PEN", currencySymbol: "S/" },
  { name: "Philippines", capital: "Manille", currencyName: "peso philippin", currencyCode: "PHP", currencySymbol: "₱" },
  { name: "Pologne", capital: "Varsovie", currencyName: "złoty", currencyCode: "PLN", currencySymbol: "zł" },
  { name: "Portugal", capital: "Lisbonne", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Qatar", capital: "Doha", currencyName: "riyal qatari", currencyCode: "QAR", currencySymbol: "ر.ق" },
  { name: "République tchèque", capital: "Prague", currencyName: "couronne tchèque", currencyCode: "CZK", currencySymbol: "Kč" },
  { name: "Roumanie", capital: "Bucarest", currencyName: "leu roumain", currencyCode: "RON", currencySymbol: "lei" },
  { name: "Royaume-Uni", capital: "Londres", currencyName: "livre sterling", currencyCode: "GBP", currencySymbol: "£" },
  { name: "Russie", capital: "Moscou", currencyName: "rouble russe", currencyCode: "RUB", currencySymbol: "₽" },
  { name: "Rwanda", capital: "Kigali", currencyName: "franc rwandais", currencyCode: "RWF", currencySymbol: "FRw" },
  { name: "Sénégal", capital: "Dakar", currencyName: "franc CFA (BCEAO)", currencyCode: "XOF", currencySymbol: "FCFA" },
  { name: "Serbie", capital: "Belgrade", currencyName: "dinar serbe", currencyCode: "RSD", currencySymbol: "дин" },
  { name: "Seychelles", capital: "Victoria", currencyName: "roupie des Seychelles", currencyCode: "SCR", currencySymbol: "₨" },
  { name: "Sierra Leone", capital: "Freetown", currencyName: "leone", currencyCode: "SLE", currencySymbol: "Le" },
  { name: "Singapour", capital: "Singapour", currencyName: "dollar de Singapour", currencyCode: "SGD", currencySymbol: "$" },
  { name: "Slovaquie", capital: "Bratislava", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Slovénie", capital: "Ljubljana", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Somalie", capital: "Mogadiscio", currencyName: "shilling somalien", currencyCode: "SOS", currencySymbol: "Sh" },
  { name: "Soudan", capital: "Khartoum", currencyName: "livre soudanaise", currencyCode: "SDG", currencySymbol: "ج.س." },
  { name: "Soudan du Sud", capital: "Djouba", currencyName: "livre sud-soudanaise", currencyCode: "SSP", currencySymbol: "£" },
  { name: "Sri Lanka", capital: "Sri Jayawardenapura Kotte", currencyName: "roupie srilankaise", currencyCode: "LKR", currencySymbol: "₨", note: "Capitale administrative ; Colombo est la capitale commerciale." },
  { name: "Suède", capital: "Stockholm", currencyName: "couronne suédoise", currencyCode: "SEK", currencySymbol: "kr" },
  { name: "Suisse", capital: "Berne", currencyName: "franc suisse", currencyCode: "CHF", currencySymbol: "Fr" },
  { name: "Suriname", capital: "Paramaribo", currencyName: "dollar du Suriname", currencyCode: "SRD", currencySymbol: "$" },
  { name: "Syrie", capital: "Damas", currencyName: "livre syrienne", currencyCode: "SYP", currencySymbol: "ل.س" },
  { name: "Tadjikistan", capital: "Douchanbé", currencyName: "somoni", currencyCode: "TJS", currencySymbol: "SM" },
  { name: "Tanzanie", capital: "Dodoma", currencyName: "shilling tanzanien", currencyCode: "TZS", currencySymbol: "TSh", note: "Capitale officielle ; Dar es Salaam est la capitale économique." },
  { name: "Tchad", capital: "N'Djaména", currencyName: "franc CFA (BEAC)", currencyCode: "XAF", currencySymbol: "FCFA" },
  { name: "Thaïlande", capital: "Bangkok", currencyName: "baht", currencyCode: "THB", currencySymbol: "฿" },
  { name: "Togo", capital: "Lomé", currencyName: "franc CFA (BCEAO)", currencyCode: "XOF", currencySymbol: "FCFA" },
  { name: "Trinité-et-Tobago", capital: "Port-d'Espagne", currencyName: "dollar de Trinité", currencyCode: "TTD", currencySymbol: "$" },
  { name: "Tunisie", capital: "Tunis", currencyName: "dinar tunisien", currencyCode: "TND", currencySymbol: "د.ت" },
  { name: "Turkménistan", capital: "Achgabat", currencyName: "manat turkmène", currencyCode: "TMT", currencySymbol: "m" },
  { name: "Turquie", capital: "Ankara", currencyName: "livre turque", currencyCode: "TRY", currencySymbol: "₺" },
  { name: "Ukraine", capital: "Kiev", currencyName: "hryvnia", currencyCode: "UAH", currencySymbol: "₴" },
  { name: "Uruguay", capital: "Montevideo", currencyName: "peso uruguayen", currencyCode: "UYU", currencySymbol: "$" },
  { name: "Vanuatu", capital: "Port-Vila", currencyName: "vatu", currencyCode: "VUV", currencySymbol: "VT" },
  { name: "Vatican", capital: "Cité du Vatican", currencyName: "euro", currencyCode: "EUR", currencySymbol: "€" },
  { name: "Venezuela", capital: "Caracas", currencyName: "bolívar", currencyCode: "VES", currencySymbol: "Bs" },
  { name: "Viêt Nam", capital: "Hanoï", currencyName: "đồng", currencyCode: "VND", currencySymbol: "₫" },
  { name: "Yémen", capital: "Sanaa", currencyName: "rial yéménite", currencyCode: "YER", currencySymbol: "﷼" },
  { name: "Zambie", capital: "Lusaka", currencyName: "kwacha zambien", currencyCode: "ZMW", currencySymbol: "ZK" },
  { name: "Zimbabwe", capital: "Harare", currencyName: "dollar zimbabwéen", currencyCode: "ZWL", currencySymbol: "$" },
];
