# -*- coding: utf-8 -*-
"""Ajustements de difficulté (conceptId -> difficulty) appliqués par le builder.
But : majorité easy/medium, quelques hard/expert (calibration quiz grand public).
"""
DIFFICULTY_OVERRIDES = {
    # ---- Mythologie grecque : hard -> medium ----
    "hera-attribute-peacock": "medium",
    "hades-helm-of-darkness": "medium",
    "ares-aphrodite-affair": "medium",
    "dionysus-born-from-zeus-thigh": "medium",
    "cronos-overthrows-ouranos": "medium",
    "cronos-devours-children": "medium",
    "pandora-elpis-remains": "medium",
    "heracles-mother-alcmene": "medium",
    "perseus-andromeda": "medium",
    "aegeus-throws-himself-into-sea": "medium",
    "oedipus-marries-jocaste": "medium",
    "theseus-son-of-aegeus": "medium",
    "heracles-strangles-nemean-lion": "medium",
    "heracles-hydra-cauterizes-necks": "medium",
    "heracles-hesperides-apples-atlas": "medium",
    "heracles-stymphalian-birds": "medium",
    "heracles-erymanthian-boar": "medium",
    "charon-obol-payment": "medium",
    "lethe-river-of-forgetting": "medium",
    "minos-rhadamanthus-judges": "medium",
    "tartarus-deepest-abyss": "medium",
    "erinyes-vengeance-goddesses": "medium",
    "labyrinth-of-cnossos": "medium",
    "colchis-golden-fleece": "medium",
    "mount-ida-judgment-of-paris": "medium",
    "sparta-city-of-menelaus": "medium",
    "aegean-sea-named-after-aegeus": "medium",
    "medusa-only-mortal-gorgon": "medium",
    "chiron-wise-centaur-tutor": "easy",
    "harpies-snatching-creatures": "medium",
    "calypso-detains-odysseus": "medium",
    "aeneas-flees-troy": "medium",
    "symbol-aegis-zeus-athena": "medium",
    "symbol-laurel-apollo": "medium",
    # ---- Mythologie grecque : hard -> easy ----
    "poseidon-earthquakes-horses": "easy",
    "apollo-twin-of-artemis": "easy",
    "hephaestus-lame": "easy",
    "judgment-of-paris-apple": "easy",
    "achilles-drags-hector-body": "easy",
    "achilles-killed-by-paris": "easy",
    "odysseus-resists-sirens-mast": "easy",
    "telemachus-son-of-odysseus": "easy",
    "homer-blind-aoidos": "easy",
    "scylla-and-charybdis": "easy",
    # ---- Mythologie grecque : expert -> hard ----
    "heracles-iolaus-hydra-helper": "hard",
    "heracles-cerynitian-hind": "hard",
    "heracles-cretan-bull": "hard",
    # ---- Mythologie égyptienne : hard -> medium ----
    "khepri-scarab-morning-form": "medium",
    "osiris-dismembered-fourteen-pieces": "medium",
    "seth-unknown-animal": "medium",
    "thoth-restores-eye-of-horus": "medium",
    "hathor-sistrum-instrument": "medium",
    "amun-the-hidden-one": "medium",
    "primeval-mound": "medium",
    "fields-of-ialu": "medium",
    "osiris-green-skin": "medium",
    "sekhmet-wife-of-ptah": "medium",
    "bastet-cult-center-bubastis": "medium",
    "ptah-patron-of-artisans": "medium",
    "khnum-ram-headed-potter": "medium",
    "djed-pillar-stability": "medium",
    "mummification-seventy-days": "medium",
    "canopic-jars-organs": "medium",
    "duat-the-underworld": "medium",
    # ---- Mythologie égyptienne : hard -> easy ----
    "khafre-great-sphinx": "easy",
    "ramses-ii-abu-simbel": "easy",
    "great-pyramid-last-standing-wonder": "easy",
    # ---- Mythologie égyptienne : expert -> hard ----
    "forty-two-assessors": "hard",
    "ba-the-bird-soul": "hard",
    # ---- Philosophie : hard -> medium ----
    "plato-intelligible-world": "medium",
    "aristotle-act-and-potency": "medium",
    "aristotle-final-cause": "medium",
    "spinoza-deus-sive-natura": "medium",
    "kant-copernican-revolution": "medium",
    "hegel-dialectical-method": "medium",
    "nietzsche-will-to-power": "medium",
    "epictetus-former-slave": "medium",
    "seneca-tutor-of-nero": "medium",
    "marcus-aurelius-successor-commodus": "medium",
    "hume-problem-of-induction": "medium",
    "wittgenstein-tractatus-final-proposition": "medium",
    "sartre-bad-faith": "medium",
    "arendt-labor-work-action": "medium",
    "rawls-veil-of-ignorance": "medium",
    "foucault-biopower": "medium",
    "popper-open-society": "medium",
    # ---- Philosophie : hard -> easy ----
    "camus-sisyphus-happy": "easy",
    "freud-interpretation-of-dreams": "easy",
    "sartre-refused-nobel-prize": "easy",
    # ---- Philosophie : expert -> hard ----
    "stoic-three-parts-of-philosophy": "hard",
    "chrysippus-second-founder": "hard",
    "cleanthes-hymn-to-zeus": "hard",
}
